---
# yamllint disable rule:line-length
services:
  infrahub-server:
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    pull_policy: always
    command: >
      gunicorn --config backend/infrahub/serve/gunicorn_config.py --logger-class infrahub.serve.log.GunicornLogger infrahub.server:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=INFO"
      - "INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SECURITY_SECRET_KEY=327f747f-efac-42be-9e73-999f08f86b92"
      - "INFRAHUB_ALLOW_ANONYMOUS_ACCESS=true"
      - "INFRAHUB_TRACE_ENABLE=${INFRAHUB_TRACE_ENABLE:-false}"
      - "INFRAHUB_TRACE_INSECURE=${INFRAHUB_TRACE_INSECURE:-true}"
      - "INFRAHUB_TRACE_EXPORTER_TYPE=${INFRAHUB_TRACE_EXPORTER_TYPE:-otlp}"
      - "INFRAHUB_TRACE_EXPORTER_ENDPOINT=${INFRAHUB_TRACE_EXPORTER_ENDPOINT:-http://jaeger:4317}"
      - "OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES:-}"
      - "INFRAHUB_DB_TYPE=${INFRAHUB_DB_TYPE}"
      - "INFRAHUB_BROKER_DRIVER=${INFRAHUB_BROKER_DRIVER:-rabbitmq}"
      - "INFRAHUB_BROKER_ADDRESS=${INFRAHUB_BROKER_ADDRESS:-message-queue}"
      - "INFRAHUB_BROKER_PORT=${INFRAHUB_BROKER_PORT:-5672}"
      - "INFRAHUB_BROKER_USERNAME=${INFRAHUB_BROKER_USERNAME:-infrahub}"
      - "INFRAHUB_BROKER_PASSWORD=${INFRAHUB_BROKER_PASSWORD:-infrahub}"
      - "INFRAHUB_CACHE_DRIVER=${INFRAHUB_CACHE_DRIVER:-redis}"
      - "INFRAHUB_CACHE_ADDRESS=${INFRAHUB_CACHE_ADDRESS:-cache}"
      - "INFRAHUB_CACHE_PORT=${INFRAHUB_CACHE_PORT:-6379}"
    volumes:
      - "storage_data:/opt/infrahub/storage"
    tty: true
    labels:
      com.github.run_id: "${GITHUB_RUN_ID:-unknown}"
      com.github.job: "${JOB_NAME:-unknown}"
    healthcheck:
      test: curl -s -f -o /dev/null http://localhost:8000/api/schema/summary || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  infrahub-git:
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    pull_policy: always
    command: infrahub git-agent start --debug
    restart: unless-stopped
    depends_on:
      - infrahub-server
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_ADDRESS=http://infrahub-server:8000"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=DEBUG"
      - "INFRAHUB_SDK_API_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SDK_TIMEOUT=20"
      - "INFRAHUB_TRACE_ENABLE=${INFRAHUB_TRACE_ENABLE:-false}"
      - "INFRAHUB_TRACE_INSECURE=${INFRAHUB_TRACE_INSECURE:-true}"
      - "INFRAHUB_TRACE_EXPORTER_TYPE=${INFRAHUB_TRACE_EXPORTER_TYPE:-otlp}"
      - "INFRAHUB_TRACE_EXPORTER_ENDPOINT=${INFRAHUB_TRACE_EXPORTER_ENDPOINT:-http://jaeger:4317}"
      - "OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES:-}"
      - "INFRAHUB_DB_TYPE=${INFRAHUB_DB_TYPE}"
      - "INFRAHUB_BROKER_DRIVER=${INFRAHUB_BROKER_DRIVER:-rabbitmq}"
      - "INFRAHUB_BROKER_ADDRESS=${INFRAHUB_BROKER_ADDRESS:-message-queue}"
      - "INFRAHUB_BROKER_PORT=${INFRAHUB_BROKER_PORT:-5672}"
      - "INFRAHUB_BROKER_USERNAME=${INFRAHUB_BROKER_USERNAME:-infrahub}"
      - "INFRAHUB_BROKER_PASSWORD=${INFRAHUB_BROKER_PASSWORD:-infrahub}"
      - "INFRAHUB_CACHE_DRIVER=${INFRAHUB_CACHE_DRIVER:-redis}"
      - "INFRAHUB_CACHE_ADDRESS=${INFRAHUB_CACHE_ADDRESS:-cache}"
      - "INFRAHUB_CACHE_PORT=${INFRAHUB_CACHE_PORT:-6379}"
    volumes:
      - "git_data:/opt/infrahub/git"
      - "git_remote_data:/remote"
    tty: true
    labels:
      com.github.run_id: "${GITHUB_RUN_ID:-unknown}"
      com.github.job: "${JOB_NAME:-unknown}"

volumes:
  git_data:
  git_remote_data:
  storage_data:
