---
# yamllint disable rule:line-length
services:
  infrahub-server:
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    command: >
      gunicorn --config backend/infrahub/serve/gunicorn_config.py -w ${GUNICORN_WORKERS} --logger-class infrahub.serve.log.GunicornLogger infrahub.server:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - "${INFRAHUB_SERVER_PORT:-8000}:8000"
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=INFO"
      - "INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SECURITY_SECRET_KEY=327f747f-efac-42be-9e73-999f08f86b92"
      - "INFRAHUB_ALLOW_ANONYMOUS_ACCESS=true"
      - "INFRAHUB_DB_TYPE=${INFRAHUB_DB_TYPE}"
      - "INFRAHUB_BROKER_DRIVER=${INFRAHUB_BROKER_DRIVER:-rabbitmq}"
      - "INFRAHUB_BROKER_ADDRESS=${INFRAHUB_BROKER_ADDRESS:-message-queue}"
      - "INFRAHUB_BROKER_PORT=${INFRAHUB_BROKER_PORT:-5672}"
      - "INFRAHUB_BROKER_USERNAME=${INFRAHUB_BROKER_USERNAME:-infrahub}"
      - "INFRAHUB_BROKER_PASSWORD=${INFRAHUB_BROKER_PASSWORD:-infrahub}"
      - "INFRAHUB_CACHE_DRIVER=${INFRAHUB_CACHE_DRIVER:-redis}"
      - "INFRAHUB_CACHE_ADDRESS=${INFRAHUB_CACHE_ADDRESS:-cache}"
      - "INFRAHUB_CACHE_PORT=${INFRAHUB_CACHE_PORT:-6379}"
    volumes:
      - ../:/source
      - "storage_data:/opt/infrahub/storage"
    tty: true
    labels:
      com.github.run_id: "${GITHUB_RUN_ID:-unknown}"
      com.github.job: "${JOB_NAME:-unknown}"
    healthcheck:
      test: curl -s -f -o /dev/null http://localhost:8000/api/schema/summary || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  database:
    ports:
      - "${INFRAHUB_DB_PORT:-7687}:7687"

volumes:
  storage_data:
