[tool.poetry]
name = "infrahub"
version = "0.2.0"
description = ""
authors = ["Damien Garros <damien@opsmill.com>"]

packages = [
    { include = "infrahub", from = "backend" },
    { include = "infrahub_ctl", from = "infrahub_ctl" },
    { include = "infrahub_client", from = "python_sdk"},
    { include = "infrahub_sync", from = "sync/infrahub-sync"},
    { include = "diffsync", from = "sync/diffsync"},
]

[tool.poetry.dependencies]
python = "^3.8"
rich = "^13.3"
pendulum = "~2.1"
typer = "^0.7"
Jinja2 = "^3.1"
httpx = "^0.23"
toml = "^0.10.2"
jsonlines = "^3.0.0"
deepdiff = "^5.8.1"
ujson = "^5.7"

[tool.poetry.group.server.dependencies]
fastapi = "~0.89"
uvicorn = {version = "~0.20", extras = ["standard"]}
gunicorn = "^20.1"
graphene = "~3.2"
neo4j = "~5.5"
starlette-exporter = "^0.12.0"
GitPython = "^3.1"
aio-pika = "^8.3"

[tool.poetry.group.sdk.dependencies]
pydantic = "^1.10"

[tool.poetry.group.cli.dependencies]
GitPython = "^3.1"

[tool.poetry.group.perf.dependencies]
locust = "^2.13.1"

[tool.poetry.group.dev.dependencies]
black = "*"
pytest = "*"
yamllint = "*"
pylint = "*"
flake8 = "^5.0"
mypy = "*"
ipython = "*"
pytest-asyncio = "*"
requests = "*"
pre-commit = "^2.20.0"
isort = "*"
autoflake = "*"
pytest-clarity = "^1.0.1"
pytest-httpx = "^0.21.2"
types-toml = "^0.10.8"
types-ujson = "^5.7.0.1"
types-pyyaml = "^6.0.12.8"


[tool.poetry.group.sync.dependencies]
dagster = "^1.1.19"
dagit = "^1.1.19"
structlog = "^22.3.0"
pynetbox = "^7.0.1"
pynautobot = "^1.4.0"

[tool.poetry.scripts]
infrahub = "infrahub.cli:app"
infrahubctl = "infrahub_ctl.cli:app"
infrahub-git-credential = "infrahub.git_credential.helper:app"
infrahub-git-askpass = "infrahub.git_credential.askpass:app"
infrahub-sync = "infrahub_sync.cli:app"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
        /(
          \.git
        | \.tox
        | \.venv
        | env/
        | _build
        | build
        | dist
        | examples
        )/
    '''

[tool.isort]
profile = "black"
known_first_party = [ "infrahub" , "infrahub_client", "infrahub_ctl" ]

[tool.coverage.run]
branch = true

[tool.pylint.general]
extension-pkg-whitelist = [
    "pydantic",
    "ujson",
]

[tool.pylint.format]
disable = "logging-fstring-interpolation"

[tool.pylint.basic]
# No docstrings required for private methods (Pylint default), or for test_ functions.
no-docstring-rgx="^(_|test_)"

[tool.pylint.messages_control]
# Line length is enforced by Black, so pylint doesn't need to check it.
# Pylint and Black disagree about how to format multi-line arrays; Black wins.
disable = """,
    line-too-long,
    missing-module-docstring,
    missing-function-docstring,
    missing-class-docstring,
    consider-using-from-import,
    invalid-name,
    too-many-arguments,
    too-many-locals,
    keyword-arg-before-vararg,
    too-few-public-methods,
    too-many-instance-attributes,
    fixme,
    consider-using-f-string,
    protected-access,
    cyclic-import,
    import-self,
    wrong-import-order,
    """

[tool.pylint.miscellaneous]
notes = """,
    FIXME,
    XXX,
    """

[tool.pylint.similarities]
min-similarity-lines = 20

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
    "tests"
]
filterwarnings = [
    "ignore:Module already imported so cannot be rewritten",
    "ignore:the imp module is deprecated"
]

[tool.mypy]
pretty = true
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
