---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-infrahub-server
  labels:
    service: infrahub-server
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.infrahubServer.replicas | default 1 }}
  selector:
    matchLabels:
      service: infrahub-server
    {{- include "infrahub-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: infrahub-server
      {{- include "infrahub-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args: {{- toYaml .Values.infrahubServer.infrahubServer.args | nindent 12 }}
          {{- with .Values.infrahubServer.infrahubServer.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.global.infrahubRepository }}:{{ .Values.global.infrahubTag | default .Chart.AppVersion }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.messageQueue.messageQueue.imagePullPolicy }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - wget -O /dev/null http://localhost:{{ (index .Values.infrahubServer.ports 0).port }}/api/schema || exit 1
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          name: infrahub-server
          ports:
          {{- range .Values.infrahubServer.ports }}
          {{- if eq .name "infrahub-gui" }}
            - containerPort: {{ .targetPort }}
              hostPort: {{ .port }}
              protocol: TCP
              name: {{ quote .name }}
          {{- end }}
          {{- end }}
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /opt/infrahub/storage
              name: infrahub-server-storage-data
            - name: config-volume
              mountPath: /config
      restartPolicy: Always
      volumes:
        {{- if not .Values.infrahubServer.persistence.enabled }}
        - name: infrahub-server-storage-data
          emptyDir: {}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ include "infrahub-helm.fullname" . }}-infrahub-config
  {{- if and .Values.infrahubServer.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: infrahub-server-storage-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.infrahubServer.persistence.size | quote }}
        {{- with .Values.infrahubServer.persistence.storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-infrahub-server
  labels:
    service: infrahub-server
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.infrahubServer.type }}
  selector:
    service: infrahub-server
  {{- include "infrahub-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.infrahubServer.ports | toYaml | nindent 4 }}
