---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-infrahub-git
  labels:
    service: infrahub-git
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.infrahubGit.replicas | default 1 }}
  selector:
    matchLabels:
      service: infrahub-git
    {{- include "infrahub-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: infrahub-git
      {{- include "infrahub-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args: {{- toYaml .Values.infrahubGit.infrahubGit.args | nindent 12 }}
          {{- with .Values.infrahubGit.infrahubGit.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.global.infrahubRepository }}:{{ .Values.global.infrahubTag | default .Chart.AppVersion }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.messageQueue.messageQueue.imagePullPolicy }}
          name: infrahub-git
          resources: {}
          tty: true
          volumeMounts:
            - name: git-data
              mountPath: /opt/infrahub/git
            - name: config-volume
              mountPath: /config
      restartPolicy: Always
      volumes:
        {{- if not .Values.infrahubGit.persistence.enabled }}
        - name: git-data
          emptyDir: {}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ include "infrahub-helm.fullname" . }}-infrahub-config
  {{- if and .Values.infrahubGit.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: git-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.infrahubGit.persistence.size | quote }}
        {{- with .Values.infrahubGit.persistence.storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
  {{- end }}
