apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-message-queue-config
data:
  rabbitmq.conf: |-
    ## Username and password
    ##
    default_user = {{ .Values.messageQueue.auth.username }}
    {{- if and (not .Values.messageQueue.auth.securePassword) .Values.messageQueue.auth.password }}
    default_pass = {{ .Values.messageQueue.auth.password }}
    {{- end }}
    # Set default permissions for the default user
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*

    {{- if .Values.messageQueue.metrics.enabled }}
    ## Prometheus metrics
    ##
    {{- range .Values.messageQueue.ports }}
    {{- if eq .name "metrics" }}
    prometheus.tcp.port = {{ .port }}
    {{- end }}
    {{- end }}
    {{- end }}
